#!/usr/bin/env python3
"""Analyze a .docx file for likely AI-generated content.

Usage:
  python analyze_docx.py input.docx --output report.html

Requires: python-docx, openai (optional)
Set OPENAI_API_KEY to use OpenAI-based detection; otherwise a heuristic detector runs.
"""
import os
import sys
import json
import argparse
import re
from collections import Counter
from docx import Document
from html import escape
import math

try:
    import openai
except Exception:
    openai = None


def load_paragraphs(path):
    doc = Document(path)
    paras = []
    for i, p in enumerate(doc.paragraphs):
        text = p.text.strip()
        if not text:
            continue
        paras.append({
            "index": i,
            "text": text,
            "length": len(text),
        })
    return paras


def heuristic_score(text):
    # Lightweight heuristic to estimate AI-likelihood (0-100)
    words = text.split()
    if not words:
        return 0
    avg_word_len = sum(len(w) for w in words) / len(words)
    punctuation = sum(1 for ch in text if ch in '.!,;:?')
    sentences = max(1, text.count('.') + text.count('!') + text.count('?'))
    avg_sentence_len = len(words) / sentences

    repetitiveness = 0
    lowered = [w.lower().strip('.,!?:;"\'') for w in words]
    unique = len(set(lowered))
    repetitiveness = 1 - (unique / len(words))

    score = 0
    # AI text often has moderate sentence length and lower repetitiveness
    score += max(0, (avg_word_len - 4.0) * 5)
    score += max(0, (avg_sentence_len - 12) * 2)
    score += repetitiveness * 30
    score += (punctuation / max(1, len(text))) * 100

    # normalize
    score = max(0, min(100, score))
    return round(score, 1)


def openai_score(text, model="gpt-3.5-turbo", retries=1):
    prompt = (
        "You are a content classifier. Respond with a JSON object exactly like:\n"
        "{\"score\": NUMBER, \"label\": \"AI\"|\"Human\", \"reason\": \"short text\"}\n"
        "Where score is the percentage likelihood the text was generated by an AI (0-100).\n"
        "Classify only the following input and keep the JSON compact.\n\n"
        "Input:\n" + text
    )
    try:
        resp = openai.ChatCompletion.create(
            model=model,
            messages=[{"role":"system","content":"You are a concise classifier."},
                      {"role":"user","content":prompt}],
            temperature=0.0,
            max_tokens=200,
        )
        content = resp["choices"][0]["message"]["content"].strip()
        # try to find JSON in content
        if content.startswith('```'):
            # strip fences
            content = '\n'.join(line for line in content.splitlines() if not line.startswith('```'))
        return json.loads(content)
    except Exception:
        return None


def analyze(paragraphs, use_openai=False):
    results = []
    for p in paragraphs:
        text = p['text']
        if use_openai and openai is not None and os.getenv('OPENAI_API_KEY'):
            out = openai_score(text)
            if out and 'score' in out:
                score = float(out['score'])
                label = out.get('label', 'AI' if score >= 50 else 'Human')
                reason = out.get('reason', '')
            else:
                score = heuristic_score(text)
                label = 'AI' if score >= 50 else 'Human'
                reason = 'heuristic fallback'
        else:
            score = heuristic_score(text)
            label = 'AI' if score >= 50 else 'Human'
            reason = 'heuristic'

        results.append({
            'index': p['index'],
            'text': text,
            'length': p['length'],
            'score': score,
            'label': label,
            'reason': reason,
        })
    return results


def normalize_text_for_plagiarism(text):
    cleaned = re.sub(r'[^A-Za-z0-9\s]', ' ', text.lower())
    return [token for token in cleaned.split() if token]


def make_ngrams(tokens, size=5):
    return [' '.join(tokens[i:i+size]) for i in range(len(tokens) - size + 1)]


def plagiarism_score(text, all_texts):
    tokens = normalize_text_for_plagiarism(text)
    if not tokens:
        return 0.0

    all_tokens = [normalize_text_for_plagiarism(other) for other in all_texts]
    all_ngrams = Counter()
    for token_list in all_tokens:
        all_ngrams.update(make_ngrams(token_list, size=5))

    ngrams = make_ngrams(tokens, size=5)
    duplicate_ngrams = sum(1 for gram in ngrams if gram and all_ngrams[gram] > 1)
    ngram_ratio = duplicate_ngrams / max(1, len(ngrams))

    sentences = [s.strip() for s in re.split(r'[.!?]', text) if s.strip()]
    all_sentences = [s.strip().lower() for other in all_texts for s in re.split(r'[.!?]', other) if s.strip()]
    repeated_sentences = sum(1 for s in sentences if all_sentences.count(s.lower()) > 1)
    sentence_ratio = repeated_sentences / max(1, len(sentences))

    score = ngram_ratio * 90 + min(1.0, sentence_ratio * 1.5) * 40
    score = max(0, min(100, score))
    return round(score, 1)


def plagiarism_label(score):
    if score >= 60:
        return 'High'
    if score >= 35:
        return 'Medium'
    return 'Low'


def plagiarism_analyze(paragraphs):
    all_texts = [p['text'] for p in paragraphs]
    results = []
    for p in paragraphs:
        score = plagiarism_score(p['text'], all_texts)
        label = plagiarism_label(score)
        reason = (
            'High duplicate content found inside document.' if score >= 60 else
            'Some repeated phrasing suggests possible plagiarism.' if score >= 35 else
            'Low internal duplication detected.'
        )
        results.append({
            'index': p['index'],
            'text': p['text'],
            'length': p['length'],
            'score': score,
            'label': label,
            'reason': reason,
            'plagiarism_score': score,
            'plagiarism_label': label,
        })
    return results


def plagiarism_aggregate(results):
    total_chars = sum(r['length'] for r in results) or 1
    weighted = sum(r['score'] * (r['length'] / total_chars) for r in results)
    overall = round(weighted, 1)
    label = plagiarism_label(overall)
    return {
        'overall_score': overall,
        'plagiarism_score': overall,
        'plagiarism_label': label,
        'high_spots': [r for r in results if r['score'] >= 60],
    }


def aggregate(results):
    total_chars = sum(r['length'] for r in results) or 1
    weighted = sum(r['score'] * (r['length'] / total_chars) for r in results)
    overall = round(weighted, 1)
    high_spots = [r for r in results if r['score'] >= 60]
    return {'overall_score': overall, 'high_spots': high_spots}


def generate_html(results, aggr, out_path):
    rows = []
    for r in results:
        color = '#ffd6d6' if r['score'] >= 60 else ('#fff7cc' if r['score'] >= 40 else '#e8ffe8')
        snippet = escape(r['text'])
        rows.append(f"<div style=\"background:{color};padding:10px;margin:6px;border-radius:6px;\"><strong>Paragraph {r['index']} — {r['label']} ({r['score']}%)</strong><div style=\"margin-top:6px;white-space:pre-wrap;\">{snippet}</div><div style=\"font-size:90%;color:#333;margin-top:6px;\">Reason: {escape(r['reason'])}</div></div>")

    html = f"""
    <html>
    <head><meta charset="utf-8"><title>AI Detection Report</title></head>
    <body style="font-family:Arial,Helvetica,sans-serif;margin:20px;">
      <h1>AI Detection Report</h1>
      <p><strong>Overall AI-likelihood:</strong> {aggr['overall_score']}%</p>
      <h2>Paragraphs</h2>
      {''.join(rows)}
    </body>
    </html>
    """
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(html)


def main(argv):
    parser = argparse.ArgumentParser(description='Analyze .docx for AI-generated content')
    parser.add_argument('input', help='Input .docx file')
    parser.add_argument('--output', '-o', help='Output HTML report', default='report.html')
    parser.add_argument('--json', '-j', help='Output JSON results', default='results.json')
    parser.add_argument('--no-openai', action='store_true', help='Disable OpenAI even if key present')
    args = parser.parse_args(argv)

    if not os.path.exists(args.input):
        print('Input file not found:', args.input)
        sys.exit(2)

    use_openai = (not args.no_openai) and openai is not None and os.getenv('OPENAI_API_KEY')
    if (not use_openai) and os.getenv('OPENAI_API_KEY') and openai is None:
        print('Warning: OPENAI_API_KEY set but openai package not installed; falling back to heuristic')

    paragraphs = load_paragraphs(args.input)
    results = analyze(paragraphs, use_openai=use_openai)
    aggr = aggregate(results)

    with open(args.json, 'w', encoding='utf-8') as f:
        json.dump({'results': results, 'aggregate': aggr}, f, indent=2, ensure_ascii=False)

    generate_html(results, aggr, args.output)
    print(f"Wrote report: {args.output}")
    print(f"Wrote JSON: {args.json}")


if __name__ == '__main__':
    main(sys.argv[1:])
